version: "3.8"

services:
  mongo-db:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  node-backend:
    build:
      context: ./backend
    environment:
      MONGO_URL: mongodb://mongo-db:27017/mydb
    depends_on:
      - mongo-db

volumes:
  mongo-data:
